### ISSUE TITLE
mapper 4 not run

### ISSUE THREAD

**Issue by ranfengzheng** [workhorsy/dartnes#1]
"regLoad() case 2:  // Fall through to case 3"
Code cannot be run here.   
It feels incomplete.

**Comment by workhorsy** [comment]
Sorry. This project has been deprecated for several years. I don't plan on working on it anymore.

There are a few alternatives, such as JSNES
https://github.com/bfirsh/jsnes
https://github.com/bfirsh/jsnes-web

**Comment by ranfengzheng** [comment]
jsnes  also has many bugs。 mapper2  mapper5 mapper4  js not runing。 
No one answered the question。
I searched for relevant information。
The code is modeled after VirtuaNES.
I tried to write and repair mapper4 and add mapper19, etc., but the changes were too large and it has not been able to run normally.

**Comment by workhorsy** [comment]
Sorry I couldn't be of any help. I originally was going to write my own NES emulator 10 years ago. But I was unable to find good documentation on all the common mappers, and a few hardware features. Then I just settled for porting VNES. It has been so long, that I've forgotten most of the details.
